Repository Expense-Tracker-BA/Expense-Tracker, pull requests merged in 2024-09, with the labels that each got.

#13 added window design
  Docs/window_design.drawio
Labels: documentation, High Priority

#14 Frontend Skeleton - Amihai & Bayan
  src/main/java/Backend/Business_Layer/Expense.java
  src/main/java/Frontend/ExpenseTrackerApplication.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/java/com/example/expensetracker/HelloController.java
  src/main/java/module-info.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
  src/main/resources/com/example/expensetracker/hello-view.fxml
  target/classes/com/example/expensetracker/HelloApplication.class
  target/classes/com/example/expensetracker/HelloController.class
  target/classes/com/example/expensetracker/hello-view.fxml
  target/classes/module-info.class
Labels: enhancement

#15 added update option to the window design
  Docs/window_design.drawio
Labels: documentation

#16 minor changes to the table in the dashboard
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Backend/Business_Layer/Expense.java
  src/main/java/Backend/Service_Layer/Service_Controller.java
  src/main/java/DAL/DAL_Controller.java
  src/main/java/Frontend/ExpenseTrackerApplication.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/java/module-info.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
  target/classes/module-info.class
Labels: High Priority

#19 added clear button and extract all function
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Backend/Service_Layer/Service_Controller.java
  src/main/java/DAL/DAL_Controller.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: High Priority

#20 Frontend bayan
  Expenses_Tracker.db
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Backend/Service_Layer/Service_Controller.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: High Priority

#21 Frontend bayan
  Expenses_Tracker.db
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Backend/Service_Layer/Service_Controller.java
  src/main/java/DAL/DAL_Controller.java
  src/main/java/Frontend/ExpenseTrackerApplication.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: High Priority

#22 Done the Filter by Date function - both FrontEnd and updated the back…
  .idea/compiler.xml
  pom.xml
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
  target/classes/module-info.class
Labels: High Priority

#23 Frontend amihai
  src/main/java/Backend/Business_Layer/Controller.java
  src/main/java/Backend/Service_Layer/Service_Controller.java
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: High Priority

#24 fixed check_if_valid_numeric_input method
  Expenses_Tracker.db
  src/main/java/Backend/Business_Layer/Controller.java
Labels: High Priority

#27 added pie chart tab
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: Low Priority

#28 Added Bar Chart
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: Low Priority

#30 added bayan's and amihai's work
  Expenses_Tracker.db
  src/main/java/Frontend/ExpenseTrackerController.java
  src/main/resources/Frontend/ExpenseTracker-view.fxml
Labels: High Priority
